// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleStupid.Data;

namespace SimpleStupid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190514230715_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SimpleStupid.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Image"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Link"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Directory"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Text"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
